### ISSUE TITLE
Feature request: Python syntax

### ISSUE THREAD

**Issue by dreamflasher** [erg-lang/erg#13]
Great effort, always wanted to have statically typed Python. 
Please consider replacing the current syntax with Python syntax to 1) reusability of existing code 2) zero learning of new syntax needed.

**Comment by mtshiba** [comment]
I plan to integrate with Python in the following ways: https://github.com/erg-lang/erg/blob/main/doc/EN/syntax/32_integration_with_Python.md

An API typed in this way can be imported from Erg without any problems.

But maybe what you mean is a mechanism to allow Python code to be applied in Erg scripts.

There are several difficulties in this regard.
First, Erg cannot reassign variables. Allowing inline Python could break this immutability condition.
For example, let `py_call` be an API that calls Python inline (this is imaginary).

```
i = 0
py_call! """
i += 1
"""
print! i # 1
```

This ruins any effort Erg makes to check for side effects.

However, some may want such an "escape hatch", like Rust's `unsafe` function or OCaml's `Obj.magic`.
I will consider whether there is a better solution for this.

**Comment by KtlTheBest** [comment]
@dreamflasher Hi, I am not sure if that is a good idea. There is a Coconut Programming Language, which is a superset of python. And also Coconut is a functional language that supports pipes, better function definition conventions, stronger patter-matching, ADTs, etc. But in my experience, because Coconut is a Python's superset (i.e. every Python valid code must also be a valid Coconut valid code as well as the same expected execution path), the resulting syntax addition can feel clunky and somewhat difficult.

The initial idea of Erg is to provide Static Typing (something that Coconut can't provide), as well as lightweight syntax (something that ML-family languages are pretty-darn good at), and to do that, you must abandon some parts of Python syntax. In the end, what history shows, is that the less is more. It can feel daunting to learn new syntax, and the ML-syntax can look "foolish" (I know I was shocked when coming from C-style languages and couldn't believe something useful could have been written in them). But it is a necessary step to provide a Static Typing benefits without bringing down the developer with all the type boilerplate type annotations (hello Java).

In the end, if done correctly, you would feel "liberated" and get used to "if it compiles, it works".

Sorry for the long-read, but TL;DR if you want to have a very Python-ish syntax, it may be possible (like ReasonML makes syntax more JS-like to attract more JS developers), but I think that given the trade-offs, the developers are making the right choice by not choosing to bring some of Python back into the language to help them move in the right direction (Hello C++ backwards compatibility).

**Comment by mtshiba** [comment]
@KtlTheBest makes a good point.

I started developing Erg in the first place because I was dissatisfied with the Python syntax. So I did not intend to make Erg a superset of Python.

Yes, and I had discovered that there was already Coconut, a superset of Python.

The biggest danger of a Python superset is that it could be incorporated into Python itself. While JavaScript, due to its peculiarity of running in a browser, cannot change its syntax without a lot of trouble, Python could drastically change its syntax in Python 4 (if it is released). If so, Erg may become obsolete.
