### ISSUE TITLE
As a python user I don't know how to run my "hello world!" in erg

### ISSUE THREAD

**Issue by ShantanuKumar** [erg-lang/erg#31]
I just installed it locally. Now I don't know how can I play around with it.

**Comment by ShantanuKumar** [comment]
Well that was easy, I had to just type `erg` for the REPL. Not sure if this should be mentioned in [Basics](https://erg-lang.github.io/00_basic.html)

**Comment by mtshiba** [comment]
for example, just type:

```console
> erg
```

`>` mark is a prompt, just type `erg`.
Then the REPL should start.

```console
> erg
Starting the REPL server...
Connecting to the REPL server...
Erg interpreter 0.2.4 (tags/?:, 2022/08/17  0:55:12.95) on x86_64/windows
>>>
```

After that, it is the same as the Python REPL.

Or you can compile from a file.

```console
> 'print! "hello, world!"' >> hello.er

> erg hello.er
hello, world!
```

**Comment by mtshiba** [comment]
I would like to add this to the document later.

**Comment by ShantanuKumar** [comment]
I can open a pull request if that's something ok with you?

**Comment by mtshiba** [comment]
Thank you! Please.

**Comment by KetanParmar07** [comment]
Hello, sir I am interested in solving this issue. so please assign to me this issue.

**Comment by KetanParmar07** [comment]
**Now, What should I do?**

**Comment by mtshiba** [comment]
> for example, just type:
> 
> ```
> > erg
> ```
> 
> `>` mark is a prompt, just type `erg`. Then the REPL should start.
> 
> ```
> > erg
> Starting the REPL server...
> Connecting to the REPL server...
> Erg interpreter 0.2.4 (tags/?:, 2022/08/17  0:55:12.95) on x86_64/windows
> >>>
> ```
> 
> After that, it is the same as the Python REPL.
> 
> Or you can compile from a file.
> 
> ```
> > 'print! "hello, world!"' >> hello.er
> 
> > erg hello.er
> hello, world!
> ```

Please add this to the syntax/00_basic.md.

**Comment by mtshiba** [comment]
After `## Script`, add a section name such as `## REPL/File execution`.

**Comment by KetanParmar07** [comment]
In which code actor this code is to be typed and run.

Please sir, Can you share me which steps to follow?

**Comment by mtshiba** [comment]
I will write instructions. Please wait...

**Comment by mtshiba** [comment]
This issue is a documentation improvement. Please follow the instructions below to rewrite the documentation.

Here is how to do it using [GitHub desktop](https://desktop.github.com/). If you can use git, you don't have to use it.

It is also quite carefully written for those who would like to contribute to this project in the future.

1. Clone this repository (open [here](https://github.com/erg-lang/erg) using your browser, then click `code`, and click `Open with GitHub Desktop`).

<img width="939" alt="スクリーンショット 2022-08-17 14 45 20" src="https://user-images.githubusercontent.com/45118249/185046321-4894ee55-8e55-41a6-82a1-eb73737a477c.png">


3. Open doc/EN/syntax/00_basic.md (by using [VS Code](https://code.visualstudio.com/), etc.).

4. After `## Scripts` section, add a section name such as `## REPL/File Execution`.

5. In that section, insert the text I just wrote (https://github.com/erg-lang/erg/issues/31#issuecomment-1217477854).

6. Back to GitHub desktop, and create a fork (choose `To contribute ...`).

7. Commit to main.
