### ISSUE TITLE
ELS : `erg language-server` does nothing (no error, no trace)

### ISSUE THREAD

**Issue by angelozerr** [erg-lang/erg#522]
Hi,

I'm trying to start the Erg language server inside IntelliJ by using LSP4IJ by filling the command https://github.com/redhat-developer/lsp4ij/blob/main/docs/UserDefinedLanguageServer.md

I have installed erg (when I type erg command it is working).

I'm trying to start the Erg language server with terminal on Windows OS with

`erg language-server` like your vscode-erg does (the doc is strange because it says `erg --language-server` which fails.

The strange thing is when I try to use this command,  the ELS does noting even after LSP client sends initialize.

vscode-erg is working for me, but not when I try to execute in terminal `erg language-server` or in LSP4IJ.

I wonder if it exists an option to log some trace server, to understand what it happens.

I have tried too to install els like explained at https://github.com/erg-lang/erg-language-server?tab=readme-ov-file#installation, but when I execute `els` it does nothing even when LSP client sends initialize.

Thanks!

**Comment by mtshiba** [comment]
I researched this issue for a while and discovered that the reason the server appeared to do nothing was because IntelliJ was passing ELS a string id instead of an integer, which was causing the initialization to fail.

https://github.com/erg-lang/erg/blob/040811744e575b8149d6d8b802d83bffb8fff5c7/crates/els/server.rs#L725

↓

https://github.com/erg-lang/erg/blob/2d5aed6ec9e5d0e5e0bde9e76417214d2b94804c/crates/els/server.rs#L725-L726

After this change, the language server now works in my environment by specifying `/path/to/erg language-server`.

**Comment by mtshiba** [comment]
By the way, ELS outputs an error log to `.erg/els.log` when an unexpected error occurs.

**Comment by angelozerr** [comment]
I did the change like you suggested and it works perfectly now

![image](https://github.com/user-attachments/assets/6a5ede1a-4909-4aaa-adee-53d9f6091da4)

//cc @amacfie you need to update the source code from ELS like suggested at https://github.com/erg-lang/erg/issues/522#issuecomment-2358636643
